---
imagebuilder: "https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/openwrt-imagebuilder-ipq40xx-generic.Linux-x86_64.tar.xz"
feed_version: "master"

imagebuilder_disable_signature_check: true
instr_set: "arm_cortex-a7_neon-vfpv4"


switch_ports: 6
switch_int_port: 0
switch_ignore_ports: [5]
# WAN port is hardwired to VLAN2. ignore

int_port: eth0

wireless_devices:
  - name: 11a_standard
    hwmode: 11a
    path: platform/soc/a800000.wifi
    ifname_hint: wlan5
  - name: 11g_standard
    hwmode: 11g
    path: platform/soc/a000000.wifi
    ifname_hint: wlan2
