---
imagebuilder: "https://downloads.openwrt.org/releases/21.02-SNAPSHOT/targets/ath79/generic/openwrt-imagebuilder-21.02-SNAPSHOT-ath79-generic.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
imagebuilder_disable_signature_check: true
target: ath79/generic

switch_ports: 6
switch_int_port: 0
switch_ignore_ports: []

int_port: eth0

wireless_devices:
  - name: 11a_standard
    hwmode: 11a
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    hwmode: 11g
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
