---
all__packages__to_merge:
  - mtr
  - tcpdump
  - iperf3
  - luci-ssl
  - luci-app-statistics
  - collectd-mod-uptime
  - collectd-mod-ping
  - -ppp
  - -ppp-mod-ppoe

  - -wpad-basic
  - -wpad-basic-wolfssl
  - wpad-openssl
  - nftables
  - kmod-nft-bridge
