---

wireless_profiles:
  - name: disable
    devices:
      - radio: 11a_standard
        disabled: true
      - radio: 11g_standard
        disabled: true

  - name: freifunk_default
    devices:
      - radio: 11a_standard
      - radio: 11g_standard

    ifaces:
      - ssid: berlin.freifunk.net
        encryption: open
        network: dhcp
        radio: [11a_standard, 11g_standard]

      - ssid: berlin.freifunk.net Encrypted
        encryption: owe
        network: dhcp
        radio: [11a_standard, 11g_standard]

all__channel_assignments_11a_standard__to_merge:
  default: "36-20"

all__channel_assignments_11g_standard__to_merge:
  default: "13-20"
