---

wireless_profiles:
  - name: disable
    devices:
      - radio: 11a_standard
        disabled: true
      - radio: 11g_standard
        disabled: true

  - name: freifunk_default
    devices:
      - radio: 11a_standard
        legacy_rates: false
        country: DE
      - radio: 11g_standard
        legacy_rates: false
        country: DE

    ifaces:
      - mode: ap
        ssid: berlin.freifunk.net
        encryption: none
        network: dhcp
        radio: [11a_standard, 11g_standard]
        ifname_hint: ff

      - mode: ap
        ssid: berlin.freifunk.net Encrypted
        encryption: owe
        network: dhcp
        radio: [11a_standard, 11g_standard]
        ifname_hint: ffowe
        ieee80211w: 1

all__channel_assignments_11a_standard__to_merge:
  default: "36-20"

all__channel_assignments_11g_standard__to_merge:
  default: "13-20"
