---
############## WRONG VALUES #################
networks:
  - vid: 42
    role: mgmt
    prefix: 10.31.52.160/27
    assignments:
      scharni-core: 1
      scharni-switch: 2
      scharni-wilgu10: 3
      scharni-zwingli: 3
      scharni-ap1: 29
      scharni-ap2: 28
      scharni-ap3: 27
  - vid: 40
    role: dhcp
    prefix: 10.36.194.128/26
    assignments:
      scharni-core: 1

