---
all__packages__to_merge:
  - mtr
  - tcpdump
  - iperf3
  - luci-ssl
  - luci-app-statistics
  - -firewall4
  - firewall
  - ip6tables # Its not pulled in by default anymore bc fw4
  - collectd-mod-uptime
  - collectd-mod-memory
  - collectd-mod-ping
  - vnstat
  - -ppp
  - -ppp-mod-pppoe
  - -wpad-basic
  - -wpad-basic-wolfssl
  - hostapd-wolfssl
  - nftables
  - kmod-nft-bridge

all_disabled_services__to_merge:
  - "olsrd6"
