---
#ipv6_prefix: "2001:bf7:860::/56" !anpassen!!

# Mesh: 10.31.83.60/30
networks:
  #- vid: 10
  #  role: mesh
  #  name: mesh_sama
  #  prefix: 10.31.83.60/32
  #  ipv6_subprefix: -1

  - vid: 42
    role: mgmt
    prefix: 10.30.96.32/28
    gateway: 1
    dns: 1
    #ipv6_subprefix: 1
    assignments:
      lebenshilfe-core: 1
      #lebenshilfe-switch: 2
      lebenshilfe-nw-ap-2ghz: 3
      lebenshilfe-nno-ap-2ghz: 4
      lebenshilfe-sso-ap-2ghz: 5
      lebenshilfe-oso-ap-2ghz: 6

  - vid: 40
    role: dhcp
    prefix: 10.30.99.0/25
    #ipv6_subprefix: 0
    assignments:
      lebenshilfe-core: 1

location__channel_assignments_11a_standard__to_merge:
  # ap-name: Channel  Bandwidth  tx-Power
  lebenshilfe-nno-ap-2ghz: 1-20-15
  lebenshilfe-nw-ap-2ghz: 6-20-15
  lebenshilfe-sso-ap-2ghz: 11-20-15
  lebenshilfe-oso-ap-2ghz: 6-20-15
