---
imagebuilder: "https://downloads.openwrt.org/releases/19.07.5/targets/ath79/generic/openwrt-imagebuilder-19.07.5-ath79-generic.Linux-x86_64.tar.xz"

switch_ports: 7
switch_int_port: 0
switch_ignore_ports: [6]
# ignore internal wan port

int_port: eth0

wireless_devices:
  - name: 11a_standard
    hwmode: 11a
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    hwmode: 11g
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
