---
imagebuilder: "https://downloads.openwrt.org/releases/19.07.5/targets/ipq40xx/generic/openwrt-imagebuilder-19.07.5-ipq40xx-generic.Linux-x86_64.tar.xz"

switch_ports: 6
switch_int_port: 0
switch_ignore_ports: [5]
# WAN port is hardwired to VLAN2. ignore

int_port: eth0
