---
ipv6_prefix: "2001:bf7:830:8900::/56"

# Rio-Reiser got following prefixes:
# Router: 10.31.139.32/27
# --MGMT: 10.31.139.32/28
# --MESH: 10.31.139.48/28
# --DHCP: 10.31.139.128/25

networks:
  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.139.128/25
    ipv6_subprefix: 0
    assignments:
      xhain-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.139.32/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      xhain-core: 1
