---
- name: Ensure subdir {{ subdir }} exists
  file:
    path: "{{ path }}/etc/{{ subdir }}"
    state: directory
- name: Render all the config in {{ subdir }}
  template: src={{ item }} dest={{ path }}/etc/{{ subdir }}/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - "{{ role_path  }}/templates/{{ role }}/{{ subdir }}/*.j2"

