---
role_ap__packages__to_merge:
  - collectd-mod-olsrd
  - collectd-mod-exec
  - collectd-mod-conntrack
  - collectd-mod-snmp6
  - collectd-mod-ipstatistics
  - olsrd
  - olsrd-mod-arprefresh
  - olsrd-mod-dyn-gw
  - olsrd-mod-jsoninfo
  - olsrd-mod-nameservice
  - olsrd-mod-txtinfo
  - olsrd-mod-watchdog
  - kmod-ipip
  - luci-app-olsr
  - luci-app-olsr-services
  - luci-mod-falter
  - falter-berlin-fix-luci
  - luci-app-falter-owm
  - luci-app-falter-owm-ant
  - luci-app-falter-owm-cmd
  - luci-app-falter-owm-gui
  - iptables-mod-ipopt
  - kmod-ipt-ipopt
  - bird2
  - bird2c
  - babeld
  - ip-full
  - wireguard
  - wg-installer-server
  - wg-installer-server-hotplug-babeld
# Required for some ugly hack which can be removed in DC
  - iptables-mod-ipopt

role_ap__disabled_services__to_merge:
  - "dnsmasq"
  - "odhcpd"
