---
role_uplink_gw__packages__to_merge:
  
  # monitoring
  - collectd-mod-olsrd
  - collectd-mod-exec
  - collectd-mod-conntrack
  - collectd-mod-snmp6
  - collectd-mod-ipstatistics
  
  #routing
  - bird2
  - bird2c
  - babeld
  - olsrd
  - olsrd-mod-arprefresh
  - olsrd-mod-dyn-gw
  - olsrd-mod-jsoninfo
  - olsrd-mod-nameservice
  - olsrd-mod-txtinfo
  - olsrd-utils
  
  # UI and Falter-stuff
  - falter-common
  - luci-app-babeld
  - luci-app-olsr
  - luci-app-olsr-services
  - luci-mod-falter
  - luci-app-falter-owm
  - luci-app-falter-owm-ant
  - luci-app-falter-owm-cmd
  - luci-app-falter-owm-gui

  # utils
  - tcpdump-mini
  - mtr
  - ip-full
  - iperf3
  - tmux
  - vnstat
  - ethtool
  - iwinfo
  - libiwinfo-lua
  
  # tunnel
  - gre
  - wireguard-tools
  - kmod-wireguard
  - wg-installer-server
  - wg-installer-server-hotplug-babeld
  
  # kmods and stuff
  - kmod-ipip
  - kmod-ipt-ipopt
  - conntrackd
  - samplicator
  - -wpad-openssl
# Required for some ugly hack which can be removed in DC
  - iptables-mod-ipopt

role_uplink_gw__disabled_services__to_merge:
  - "dnsmasq"
  - "odhcpd"
