---
ipv6_prefix: "2001:bf7:830:8600::/56"

networks:
  - vid: 42
    role: mgmt
    prefix: 10.31.81.0/27
    gateway: 1 # Simon fragen, was das ist.
    dns: 1 # Simon fragen, was das ist.
    ipv6_subprefix: 1 # 2. subnetz aus ipv6 prefix
    assignments:        # 
      tub-core: 1


  - vid: 40
    role: dhcp
    prefix: 10.31.81.128/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      sama-core: 1


# 10.31.79.176/28 Mesh Prefix (16)
  - vid: 10
    role: mesh
    name: mesh_nord
    prefix: 10.31.79.176/32
    ipv6_subprefix: -1
  - vid: 11
    role: mesh
    name: mesh_ost
    prefix: 10.31.79.177/32
    ipv6_subprefix: -2
  - vid: 12
    role: mesh
    name: mesh_sued
    prefix: 10.31.79.178/32
    ipv6_subprefix: -3
  - vid: 13
    role: mesh
    name: mesh_west
    prefix: 10.31.79.179/32
    ipv6_subprefix: -4


# channel-bandwith-txpower in dbm
# Back to Back channel is reused
# - Hopefully rf-Shield performs :)
# Due to heavy reflections due to Vogelgitter nothing performs
