---
  name: Post-Merge Diff

  on:
    push:
      branches:
        - master

  jobs:
    compare-changes:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth:  0  # Fetch all history for all branches and tags

        - name: Compare feature branch with main before merge
          run: |
            git diff ${{ github.event.before }}..${{ github.event.after }} > diff.txt
            cat diff.txt
