---
name: Wikiupdate
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt install python3

      - name: Install dependencies
        run: pip3 install -r requirements.txt --upgrade pip

      - name: Determine changed locations
        run: |
            CHANGED_LOCATIONS=$(git diff ${{ github.event.before }}..${{ github.event.after }} --diff-filter=d --name-only | grep 'locations/' | sed 's/locations\/\(.*\)\.yml/location_\1/' | sed -z 's/-/_/g;s/\n/,/g;s/,$//')
            echo "Updating for changed locations: $CHANGED_LOCATIONS"
            echo "CHANGED_LOCATIONS=$CHANGED_LOCATIONS" >> "$GITHUB_ENV"

      - name: Update wiki.freifunk.net
        env:
          FF_WIKI_USER: ${{ vars.FF_WIKI_USER }}
          FF_WIKI_PASSWORD: ${{ secrets.FF_WIKI_PASSWORD }}
        run: |
          if [ -n "${CHANGED_LOCATIONS}" ]; then
            ansible-playbook play.yml --tags wiki --limit "$CHANGED_LOCATIONS" ||true
          else
            echo "No locations were changed. Skipping update"
          fi

  push_json_to_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML and json
        run: |
          python -m pip install pyyaml

      - name: Convert YAML to JSON and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: 'ffhener/berlin.freifunk.net'
          TARGET_BRANCH: 'main'
          TARGET_PATH: '/content/locations'
        run: |
          # Read the CHANGED_LOCATIONS environment variable
          IFS=',' read -ra LOCATIONS <<< "${{ env.CHANGED_LOCATIONS }}"

          # Loop through each location
          for location in "${LOCATIONS[@]}"; do
            # Convert YAML to JSON
            python -c "import yaml; import json; with open('locations/$location.yml', 'r') as f: data = yaml.safe_load(f); with open('$location.json', 'w') as outfile: json.dump(data, outfile)"

            # Push the JSON file to the target repository
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git target-repo
            cd target-repo
            mkdir -p "$TARGET_PATH/$location/data"
            mv "$location.json" "$TARGET_PATH/$location/data.json"
            git add "$TARGET_PATH/$location/data.json"
            git commit -m "Update location data for $location"
            git push origin $TARGET_BRANCH
            cd ..
            rm -rf target-repo
          done
